[tool.ruff]
select = ["D", "E", "F", "I", "N", "W"]
ignore = [
    "N999",  # Invalid module name (caused by cookiecutter syntax)
    "D203",  # Incompatible with D211
    "D213"  # Incompatible with D212
]

[tool.ruff.per-file-ignores]
"tests/*" = ["D"]
